[platformio]
default_envs = esp32-test

; =========================
; ESP32 Test
; =========================
[env:esp32-test]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = ../../lib/
lib_deps = libcannetwork
            https://github.com/handmade0octopus/ESP32-TWAI-CAN.git
lib_ldf_mode = chain+
monitor_speed = 9600
upload_speed = 921600
extra_scripts =
lib_archive = false