#include <Arduino.h>
#include <vehicle.hpp>
#include <SD.h>
#include <Ticker.h>
#include <esp_now.h>
#include <WiFi.h>
#include <BLEDevice.h>

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////


// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG   


// RemoteXY select connection mode and include library
#define REMOTEXY_MODE__ESP32CORE_BLE


// RemoteXY connection settings
#define REMOTEXY_BLUETOOTH_NAME "DEV_Vehicle"
#define REMOTEXY_ACCESS_PASSWORD "DEV4Life"

#include <RemoteXY.h>


// RemoteXY GUI configuration 
/*
  -- LA PROJECT --
 
  To compile this code using RemoteXY library 4.1.8 or later version
  download by link http://remotexy.com/en/library/
  To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                  
    - for ANDROID 4.18.03 or later version;
    - for iOS 1.14.1 or later version;
  
  To interact with the GUI, please refer to the manual:
  https://remotexy.com/ru/help/code/interaction/


  This source code was automatically generated by the RemoteXY editor and
  is an example for the RemoteXY library.
  Licensed under the MIT License. See the LICENSE file in the RemoteXY library
  root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license
  details.            
*/


//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////


// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG   


// RemoteXY select connection mode and include library
#define REMOTEXY_MODE__ESP32CORE_BLE


#include <BLEDevice.h>


// RemoteXY connection settings
#define REMOTEXY_BLUETOOTH_NAME "DEV_Vehicle"
#define REMOTEXY_ACCESS_PASSWORD "DEV4Life"




#include <RemoteXY.h>


// RemoteXY GUI configuration 
#pragma pack(push, 1) 
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =   // 634 bytes V19
 { 255,0,0,42,0,115,2,19,0,0,0,68,69,86,95,68,105,97,103,0,
 16,2,106,200,200,84,2,1,1,27,0,129,2,38,53,11,144,63,24,5,
 64,6,86,111,108,116,97,103,101,40,86,41,0,67,60,38,45,11,170,62,
 28,7,77,31,6,3,129,2,51,51,11,142,74,24,5,64,6,67,117,114,
 114,101,110,116,40,65,41,0,67,60,51,45,11,170,73,28,7,77,31,6,
 3,129,2,64,38,11,88,63,17,5,64,6,84,104,114,82,97,119,0,67,
 60,64,45,11,107,62,31,7,85,31,6,129,2,77,35,11,89,74,16,5,
 64,6,84,104,114,65,118,103,0,67,60,77,45,11,107,73,31,7,85,31,
 6,70,40,124,10,10,33,58,7,7,16,24,6,0,129,2,126,35,8,13,
 59,18,4,64,6,77,95,69,110,97,98,108,101,0,70,91,124,10,10,76,
 76,7,7,16,24,6,0,129,53,126,30,8,58,77,15,4,64,6,72,97,
 122,97,114,100,115,0,129,2,90,3,11,7,38,0,5,64,6,0,70,40,
 135,10,10,33,67,7,7,16,24,6,0,129,2,137,14,8,23,68,7,4,
 64,6,76,101,102,116,0,70,91,135,10,10,76,58,7,7,16,24,6,0,
 129,53,137,19,8,62,59,10,4,64,6,82,105,103,104,116,0,70,40,147,
 10,10,33,76,7,7,16,24,6,0,129,2,149,30,8,17,77,15,4,64,
 6,82,117,110,110,105,110,103,0,70,91,147,10,10,76,67,7,7,16,24,
 6,0,129,53,149,21,8,62,68,11,4,64,6,66,114,97,107,101,0,129,
 19,50,71,29,74,14,61,16,192,202,68,69,86,66,85,71,0,67,41,17,
 21,24,23,34,40,10,77,16,6,2,129,243,28,71,29,33,21,20,12,64,
 6,107,112,104,0,67,69,95,21,24,145,35,40,10,77,16,6,2,129,57,
 43,71,29,155,22,22,12,64,6,114,112,109,0,131,45,84,21,33,88,37,
 33,9,2,6,2,31,68,69,86,66,79,65,82,68,0,6,9,0,71,237,
 15,71,71,253,3,93,93,56,0,6,24,135,0,0,0,0,0,0,32,66,
 0,0,32,65,0,0,32,65,0,0,0,64,24,107,112,104,0,67,62,33,
 21,24,135,20,62,15,78,16,6,2,67,71,93,21,24,135,37,62,15,78,
 16,6,2,67,71,136,21,24,135,54,62,15,78,16,6,2,129,25,40,71,
 29,96,23,38,10,0,6,87,97,116,116,97,103,101,0,129,24,95,71,29,
 98,39,34,10,0,6,86,111,108,116,97,103,101,0,129,23,138,71,29,99,
 56,33,10,0,6,67,117,114,114,101,110,116,0,129,29,16,71,29,102,3,
 82,16,192,14,68,69,86,66,79,65,82,68,0,131,73,164,21,33,150,72,
 33,9,2,6,2,31,68,69,86,66,85,71,0,9 };
 // this structure defines all the variables and events of your control interface
struct {


   // output variables
 float app_voltage;
 float app_current;
 int16_t app_throttleR; // -32768 .. +32767
 int16_t app_throttleA; // -32768 .. +32767
 uint8_t app_motorE; // from 0 to 1
 uint8_t app_hazards; // from 0 to 1
 uint8_t app_left; // from 0 to 1
 uint8_t app_right; // from 0 to 1
 uint8_t app_running; // from 0 to 1
 uint8_t app_brake; // from 0 to 1
 float app_kph;
 float app_rpm;
 float drive_kph; // from 0 to 40
 float drive_wattage;
 float drive_voltage;
 float drive_current;


   // other variable
 uint8_t connect_flag;  // =1 if wire connected, else =0


} RemoteXY; 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////




unsigned long previousMillis = 0;
const long interval = 500;

// ---- ESP-NOW telemetry ----
// REPLACE with your receiver ESP32's MAC address
uint8_t telemetryPeer[] = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF};

typedef struct __attribute__((packed)) vehicle_telemetry {
  uint32_t timestamp_ms;
  float    kph;
  float    rpm;
  float    voltage;        // V
  float    current;        // A
  float    wattage;        // W
  int16_t  throttle_raw;
  int16_t  throttle_avg;
  uint8_t  motor_enabled;
  uint8_t  hazard;
  uint8_t  left_turn;
  uint8_t  right_turn;
  uint8_t  brake_lights;
  uint8_t  running_lights;
} vehicle_telemetry;

vehicle_telemetry g_telemetry;
esp_now_peer_info_t telemetryPeerInfo;

void OnEspNowSent(const uint8_t *mac_addr, esp_now_send_status_t status) {
  Serial.println(status == ESP_NOW_SEND_SUCCESS ? "ESP-NOW OK" : "ESP-NOW FAIL");
}

void espnow_send(void *args) {
  while (true) {
    g_telemetry.timestamp_ms   = millis();
    g_telemetry.rpm            = g_vehicle.m_motor_rpm;
    g_telemetry.kph            = (3.14f * g_vehicle.m_motor_rpm * 0.58f * 60.0f) / 1000.0f;
    g_telemetry.voltage        = g_vehicle.m_pdb_voltage / 1000.0f;
    g_telemetry.current        = g_vehicle.m_pdb_current / 1000.0f;
    g_telemetry.wattage        = (g_vehicle.m_pdb_voltage * g_vehicle.m_pdb_current) / 1000000.0f;
    g_telemetry.throttle_raw   = (int16_t)g_vehicle.m_throttle_raw;
    g_telemetry.throttle_avg   = (int16_t)g_vehicle.m_throttle_average;
    g_telemetry.motor_enabled  = g_vehicle.m_pdb_motor_enabled;
    g_telemetry.hazard         = (g_vehicle.m_peripherals_hazard == 1);
    g_telemetry.left_turn      = (g_vehicle.m_peripherals_turn == 1);
    g_telemetry.right_turn     = (g_vehicle.m_peripherals_turn == 2);
    g_telemetry.brake_lights   = (g_vehicle.m_peripherals_brakelights == 1);
    g_telemetry.running_lights = (g_vehicle.m_peripherals_backrunninglights == 1);

    esp_now_send(telemetryPeer, static_cast<uint8_t*>(&g_telemetry), sizeof(g_telemetry));
    vTaskDelay(pdMS_TO_TICKS(100));  // 10 Hz
  }
}


#define RL 22
#define HL 16
#define HR 17
#define SD_CARD_SLOT 5


#ifndef LED_BUILTIN
#define LED_BUILTIN 2
#endif


void send_all(void *args) {
 while (true) {
   g_vehicle.send_all();
   vTaskDelay(pdMS_TO_TICKS(100));
 }
}


File dataFile;
void write_to_sd(void *args) {
 while(true) {
   dataFile.print(millis());
   dataFile.print(",");
   dataFile.print(g_vehicle.m_motor_rpm);
   dataFile.print(",");
   dataFile.print(g_vehicle.m_pdb_current);
   dataFile.print(",");
   dataFile.print(g_vehicle.m_throttle_average);
   dataFile.print(",");
   dataFile.println(g_vehicle.m_throttle_raw);  // println only on the last one


   dataFile.flush();
   vTaskDelay(pdMS_TO_TICKS(100));
 }
}


bool hazard = false;
bool leftTurn = false;
bool rightTurn = false;
bool backrunningLights = false;
bool brakeLights = false;


void setup() {
 RemoteXY_Init();

  WiFi.mode(WIFI_STA);
  if (esp_now_init() == ESP_OK) {
    esp_now_register_send_cb(OnEspNowSent);
    memcpy(telemetryPeerInfo.peer_addr, telemetryPeer, 6);
    telemetryPeerInfo.channel = 0;
    telemetryPeerInfo.encrypt = false;
    if (esp_now_add_peer(&telemetryPeerInfo) == ESP_OK) {
      xTaskCreate(espnow_send, "ESPNow TX", 4096, nullptr, 4, nullptr);
      Serial.println("ESP-NOW telemetry started");
    } else {
      Serial.println("ESP-NOW: failed to add peer");
    }
  } else {
    Serial.println("ESP-NOW: init failed");
  }

 SD.begin(SD_CARD_SLOT);


 g_vehicle.init_network(DevBoard::COMMUNICATIONS);
 xTaskCreate(send_all, "Sending", 4096, nullptr, 5, nullptr);


 Serial.begin(115200);


 int count = 0;
 File countFile = SD.open("/count.txt", FILE_READ);
 if (countFile) {
   count = countFile.parseInt();
   countFile.close();
 }


 // Increment and save it back
 count++;
 SD.remove("/count.txt");
 countFile = SD.open("/count.txt", FILE_WRITE);
 countFile.println(count);
 countFile.close();


 char filename[16];
 snprintf(filename, 16, "/log%d.csv", count);


 dataFile = SD.open(filename, FILE_WRITE);
 Serial.print("Logging to: ");
 Serial.println(filename);


 dataFile.println("timestamp_ms,rpm,current,throttle_avg,throttle_raw");


 xTaskCreate(write_to_sd, "Writing to SD", 4096, nullptr, 5, nullptr);


 pinMode(LED_BUILTIN, OUTPUT);
 pinMode(HR, OUTPUT);
 pinMode(HL, OUTPUT);
 pinMode(RL, OUTPUT);


 ledcSetup(0, 5000, 8);   // channel 0, 8-bit (0–255)
 ledcAttachPin(RL, 0);
}


void readStates() {
 backrunningLights = (g_vehicle.m_peripherals_backrunninglights == 1);
 brakeLights       = (g_vehicle.m_peripherals_brakelights == 1);
 hazard            = (g_vehicle.m_peripherals_hazard == 1);
 rightTurn         = (g_vehicle.m_peripherals_turn == 2);
 leftTurn          = (g_vehicle.m_peripherals_turn == 1);
}


void loop() {
 RemoteXY_Handler();
 readStates();


 if (hazard || leftTurn) {
   digitalWrite(HL, HIGH);
 } else {
   digitalWrite(HL, LOW);
 }


 if (hazard || rightTurn) {
   digitalWrite(HR, HIGH);
 } else {
   digitalWrite(HR, LOW);
 }


 if (brakeLights) {
   ledcWrite(0, 255);  // brake
 } else if (backrunningLights) {
   ledcWrite(0, 20);   // running
 } else {
   ledcWrite(0, 0);   // running
 }


 unsigned long currentMillis = millis();
 if (currentMillis - previousMillis >= interval) {
   previousMillis = currentMillis;


   float spd = (3.14 * g_vehicle.m_motor_rpm * 0.58 * 60) / 1000.0;


   RemoteXY.app_kph        = (float)spd;
   RemoteXY.app_voltage      = (float)(g_vehicle.m_pdb_voltage/1000.0);
   RemoteXY.app_current      = (float)(g_vehicle.m_pdb_current/1000.0);
   RemoteXY.app_throttleR = (int16_t)g_vehicle.m_throttle_raw;
   RemoteXY.app_throttleA = (int16_t)g_vehicle.m_throttle_average;
   RemoteXY.app_motorE   = (uint8_t)g_vehicle.m_pdb_motor_enabled;
   RemoteXY.app_hazards   = (uint8_t)hazard;
   RemoteXY.app_left      = (uint8_t)leftTurn;
   RemoteXY.app_right     = (uint8_t)rightTurn;
   RemoteXY.app_running   = (uint8_t)(g_vehicle.m_peripherals_backrunninglights);
   RemoteXY.app_brake     = (uint8_t)brakeLights;
   RemoteXY.drive_kph = (float)spd;
   RemoteXY.drive_current = (float)(g_vehicle.m_pdb_current/1000.0);
   RemoteXY.drive_voltage = (float)(g_vehicle.m_pdb_voltage/1000.0);
   RemoteXY.drive_wattage = (float)((g_vehicle.m_pdb_voltage * g_vehicle.m_pdb_current)/1000000.0);
 }
}

