[env:comms_board]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = ../../lib/
lib_deps =
	libcannetwork
	handmade0octopus/ESP32-TWAI-CAN
lib_ldf_mode = chain+
monitor_speed = 115200
upload_speed = 921600
extra_scripts =
